### ISSUE TITLE
Questions: Setting Google configuration, credentials and Cloud SQL 

### ISSUE THREAD

**Issue by cbdelavenne** [oitmain-public/yii2-app-gae-flex#1]
Hello!

First of all, thanks for making this boilerplate of Yii 2 for GAE Flex. It's been super useful already!
With that said, I had some questions regarding additional configuration settings.

1. For Yii 2 to connect correctly to CloudSQL correctly, where would you set the `cloudsql` connection name (i.e. `your_project_name:your_region:your_instance`)?
2. Where would the Google Project ID be set?
3. Do you know if Google OAuth would work with Yii 2 (providing we give it a generated Client ID and Secret)?

Most of my questions stem from following along the [Google Cloud PHP Bookshelf App tutorial](https://cloud.google.com/php/getting-started/tutorial-app).

**Comment by patrick-yi-82** [comment]
1. Go to the advanced branch, and check out `config/db.php`, `config/web-gae.php` and env_variables section in `app.yaml.dist`
2. See second paragraph in https://cloud.google.com/appengine/docs/flexible/php/configuring-your-app-with-app-yaml#app-id. (app.yaml isn't used)

> 
> However, in the flexible environment, the project ID (app ID) is specified either:
> 
> By using gcloud init when you install the Google Cloud SDK. To view the default project ID of the gcloud tool, run gcloud config list.
> By using the gcloud config set project [YOUR_PROJECT_ID] command to set the default project ID of the gcloud tool.
> By using the --project flag when you deploy your app, for example: gcloud app deploy --project [YOUR_PROJECT_ID]

3. I never tried it, but I'm sure someone made a module of it already.

**Comment by cbdelavenne** [comment]
@patrick-yi-82 Thanks for getting back to me some quickly!

I was reviewing all the file differences between the `master` and `advanced` branched and identified:

- a number of new files (`config/web-gae.php`, `web-local.php.dist`, `models\PhpErrorHandler.php`, `web/.htaccess`, and `.env.dist`);
- the addition of the `vlucas/phpdotenv` package to `composer.json`;
- modifications to `config/db.php` to make use of `getenv` from the aforementioned package;
- modifications to `app.yaml` to specify the environment variables to use on GAE;
- modifications to `config/web.php`, `nginx-app.conf`, `web/index.php`.

Most of it is self-explanatory and makes for local dev/testing use vs GAE deployment.

While configuring my `.env.dist` file and renaming it to `.env`, I realized I have a few additional questions:

1. I navigated to the link you suggested below, but I'm still a bit lost as to what you are suggesting here:
    ```
    # google cloud default credentials for local deployment
    # https://cloud.google.com/docs/authentication/getting-started#setting_the_environment_variable
    #GOOGLE_APPLICATION_CREDENTIALS=../your-credentials.json
    ```
    Could you clarify?
2. You also have a `# debug` section that lists a `DEBUG_IP` (which I won't list here). 
    - How do you use this said `DEBUG_IP`?
    - It probably shouldn't be set to the value it's set to right now given that it is an actual IP address ;)
3. In `config/web-gae.php` and `config/web-local.php`, you have the same comment come up twice:
    ```
    // This configuration will be merged with web.php
    // See index.php for detail on merging
    ```
    What do you mean by this? Should I merge the contents of these files manually into `config/web.php`?

**Comment by cbdelavenne** [comment]
By the way, after making the changes I listed above, I ran into the following error when running locally: 

`php -S localhost:9898 -d display_errors=1 -t web`

```
exception 'ReflectionException' with message 'Class Oitmain\Yii2\Google\GoogleStorageAssetManager does not exist' in C:\workspace\yii2-gae-test\vendor\yiisoft\yii2\di\Container.php:428
Stack trace:
#0 C:\workspace\yii2-gae-test\vendor\yiisoft\yii2\di\Container.php(428): ReflectionClass->__construct('Oitmain\\Yii2\\Go...')
#1 C:\workspace\yii2-gae-test\vendor\yiisoft\yii2\di\Container.php(364): yii\di\Container->getDependencies('Oitmain\\Yii2\\Go...')
#2 C:\workspace\yii2-gae-test\vendor\yiisoft\yii2\di\Container.php(156): yii\di\Container->build('Oitmain\\Yii2\\Go...', Array, Array)
#3 C:\workspace\yii2-gae-test\vendor\yiisoft\yii2\BaseYii.php(349): yii\di\Container->get('Oitmain\\Yii2\\Go...', Array, Array)
#4 C:\workspace\yii2-gae-test\vendor\yiisoft\yii2\di\ServiceLocator.php(137): yii\BaseYii::createObject(Array)
#5 C:\workspace\yii2-gae-test\vendor\yiisoft\yii2\base\Module.php(742): yii\di\ServiceLocator->get('assetManager', true)
#6 C:\workspace\yii2-gae-test\vendor\yiisoft\yii2\base\Application.php(608): yii\base\Module->get('assetManager')
#7 C:\workspace\yii2-gae-test\vendor\yiisoft\yii2\web\View.php(225): yii\base\Application->getAssetManager()
#8 C:\workspace\yii2-gae-test\vendor\yiisoft\yii2\base\Component.php(139): yii\web\View->getAssetManager()
#9 C:\workspace\yii2-gae-test\vendor\yiisoft\yii2-debug\src\panels\AssetPanel.php(80): yii\base\Component->__get('assetManager')
#10 C:\workspace\yii2-gae-test\vendor\yiisoft\yii2-debug\src\Module.php(183): yii\debug\panels\AssetPanel->isEnabled()
#11 C:\workspace\yii2-gae-test\vendor\yiisoft\yii2-debug\src\Module.php(154): yii\debug\Module->initPanels()
#12 C:\workspace\yii2-gae-test\vendor\yiisoft\yii2\base\BaseObject.php(109): yii\debug\Module->init()
#13 C:\workspace\yii2-gae-test\vendor\yiisoft\yii2\base\Module.php(158): yii\base\BaseObject->__construct(Array)
#14 [internal function]: yii\base\Module->__construct('debug', Object(yii\web\Application), Array)
#15 C:\workspace\yii2-gae-test\vendor\yiisoft\yii2\di\Container.php(383): ReflectionClass->newInstanceArgs(Array)
#16 C:\workspace\yii2-gae-test\vendor\yiisoft\yii2\di\Container.php(156): yii\di\Container->build('yii\\debug\\Modul...', Array, Array)
#17 C:\workspace\yii2-gae-test\vendor\yiisoft\yii2\BaseYii.php(349): yii\di\Container->get('yii\\debug\\Modul...', Array, Array)
#18 C:\workspace\yii2-gae-test\vendor\yiisoft\yii2\base\Module.php(427): yii\BaseYii::createObject(Array, Array)
#19 C:\workspace\yii2-gae-test\vendor\yiisoft\yii2\base\Application.php(315): yii\base\Module->getModule('debug')
#20 C:\workspace\yii2-gae-test\vendor\yiisoft\yii2\web\Application.php(69): yii\base\Application->bootstrap()
#21 C:\workspace\yii2-gae-test\vendor\yiisoft\yii2\base\Application.php(273): yii\web\Application->bootstrap()
#22 C:\workspace\yii2-gae-test\vendor\yiisoft\yii2\base\BaseObject.php(109): yii\base\Application->init()
#23 C:\workspace\yii2-gae-test\vendor\yiisoft\yii2\base\Application.php(206): yii\base\BaseObject->__construct(Array)
#24 C:\workspace\yii2-gae-test\web\index.php(60): yii\base\Application->__construct(Array)
#25 {main}
```

My `composer.json` includes your `oitmain/yii2-gcloud-helpers` package, so I'm a bit confused!

```
{
  ...
  "minimum-stability": "dev",
  "require": {
    "php": "5.6.*",
    "yiisoft/yii2": "~2.0.0",
    "yiisoft/yii2-bootstrap": "~2.0.0",
    "yiisoft/yii2-swiftmailer": "~2.0.0",
    "oitmain/yii2-gcloud-helpers": "dev-master",
    "vlucas/phpdotenv": "^2.4",
    "ext-gd": "*",
    "twilio/sdk": "~5.18.0",
    "drewm/mailchimp-api": "dev-master"
  },
  "require-dev": {
    "yiisoft/yii2-debug": "~2.0.0",
    "yiisoft/yii2-gii": "~2.0.0",
    "yiisoft/yii2-faker": "~2.0.0",
    "codeception/base": "^2.2.3",
    "codeception/verify": "~0.3.1",
    "codeception/specify": "~0.4.3"
  },
  "config": {
    "process-timeout": 1800,
    "fxp-asset": {
      "enabled": false
    }
  },
  "scripts": {
    "post-install-cmd": [
      "yii\\composer\\Installer::postInstall"
    ],
    "post-create-project-cmd": [
      "yii\\composer\\Installer::postCreateProject",
      "yii\\composer\\Installer::postInstall"
    ]
  },
  "extra": {
    "yii\\composer\\Installer::postCreateProject": {
      "setPermission": [
        {
          "runtime": "0777",
          "web/assets": "0777",
          "yii": "0755"
        }
      ]
    },
    "yii\\composer\\Installer::postInstall": {
      "generateCookieValidationKey": [
        "config/web.php"
      ]
    }
  },
  "repositories": [
    {
      "type": "composer",
      "url": "https://asset-packagist.org"
    },
    {
      "type": "git",
      "url": "https://github.com/oitmain/yii2-gcloud-helpers"
    }
  ]
}
```

**Comment by patrick-yi-82** [comment]
1. GOOGLE_APPLICATION_CREDENTIALS 
By setting this env value, PHP Google Cloud library will automatically use that file as the default credential. (https://github.com/GoogleCloudPlatform/google-cloud-php#authentication)

2. DEBUG_IP will let you access Yii2 debug and gii module from that IP

3. In index.php, config from web-gae.php and web-local.php will automatically merge with config in web.php
```

$config = \yii\helpers\ArrayHelper::merge(
    require(__DIR__ . '/../config/web.php'),
    require(__DIR__ . '/../config/web-gae.php'),
    require(__DIR__ . '/../config/web-local.php')
);
```
